spring:
  application:
    name: EventOrganizer

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:event-organizer}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:none}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}